import { beforeEach, describe, expect, it, vi } from "vitest";
import type { OracleGatePublicEvidenceItemV1, PrivateAnswerKeyV1, PublicBlindPackageV1 } from "../../contracts/src/index.js";
import { assertActiveTrustedOracleGateRatingSetCapability, type TrustedOracleGateRatingSetCapabilityV1 } from "./oracleBlindRatingGate.js";

vi.mock("./oracleBlindRatingGate.js", () => ({
  assertActiveTrustedOracleGateRatingSetCapability: vi.fn(),
}));
vi.mock("../../contracts/src/index.js", async (original) => {
  const actual = await original<typeof import("../../contracts/src/index.js")>();
  return {
    ...actual,
    validateCompletedFormalRunArtifactChain: vi.fn(() => ({ valid: true, issues: [] })),
    validateOracleGateRatingPlanAgainstFormalSpec: vi.fn(() => ({ valid: true, issues: [] })),
    validateOracleGatePublicEvidenceAgainstBlindArtifacts: vi.fn(() => ({ valid: true, issues: [] })),
    validateOracleValueGateReportAgainstStatisticsPlan: vi.fn(() => ({ valid: true, issues: [] })),
  };
});

import { compileOracleValueGateStatistics } from "./oracleValueGateStatistics.js";

const sha=(c:string)=>c.repeat(64), arms=["transcript_only","static_final_board","uniform_frame","oracle_delta"] as const;
function fixture(){
 const publicItems:PublicBlindPackageV1["items"]=[],entries:PrivateAnswerKeyV1["entries"]=[],evidenceItems:OracleGatePublicEvidenceItemV1[]=[],ledgerItems:[any[],any[]]=[[],[]];let index=0;
 for(const teacher of ["teacher-a","teacher-b"])for(const seed of [11,23,47])for(const arm of arms){const blind=`B-${index.toString(16).padStart(64,"0")}`,responseSha=(index+100).toString(16).padStart(64,"0");publicItems.push({blind_id:blind,response:{fixture:index},response_sha256:responseSha});entries.push({blind_id:blind,request_id:`req-${index}`,idempotency_key:(index+200).toString(16).padStart(64,"0"),case_id:`case-${teacher}`,arm,seed,teacher_id:teacher,source_video_id:`video-${teacher}`,window_id:`window-${teacher}`,response_sha256:responseSha});const evidence={blind_id:blind,response_sha256:responseSha,claim_units:[{claim_id:"c0",claim_index:0,content:"Claim zero"},{claim_id:"c1",claim_index:1,content:"Claim one"}],evidence_units:[{unit_id:"e0",kind:"speech" as const,sequence_index:0,content:"Evidence zero"},{unit_id:"e1",kind:"board_delta" as const,sequence_index:1,content:"Evidence one"}],eligible_evidence_unit_ids:["e0","e1"],board_edit_unit_ids:["e1"],temporal_pairs:[{pair_id:"p0",before_unit_id:"e1",after_unit_id:"e0"}]};evidenceItems.push(evidence);const quality=arm==="oracle_delta"?2:arm==="static_final_board"?1:0;for(const list of ledgerItems)list.push({blind_id:blind,response_sha256:responseSha,evidence_item_sha256:sha("a"),claim_judgments:[{claim_id:"c0",claim_index:0,supported:quality>=1,evidence_unit_ids:quality>=1?["e0"]:[]},{claim_id:"c1",claim_index:1,supported:quality===2,evidence_unit_ids:quality===2?["e1"]:[]}],covered_edit_unit_ids:quality===2?["e1"]:[],temporal_judgments:[{pair_id:"p0",correct_order:quality===2}]});index++;}
 const pub={schema_version:"oracle-gate-public-blind-package-v1",package_sha256:sha("1"),run_commitment_sha256:sha("2"),rubric_version:"rubric-v1",rubric_sha256:sha("3"),blinding_statement:"metadata_blinded_no_pairing_exposed",item_count:publicItems.length,items:publicItems} as PublicBlindPackageV1;
 const key={schema_version:"oracle-gate-private-answer-key-v1",answer_key_sha256:sha("4"),run_sha256:sha("2"),public_package_sha256:sha("1"),blind_secret_commitment_sha256:sha("5"),blinding_scheme:"hmac-sha256-run-request-v1",created_at:"2026-08-13T00:00:00.000Z",entries} as PrivateAnswerKeyV1;
 const statistics={schema_version:"oracle-gate-statistics-plan-v1",statistics_plan_sha256:sha("6"),metric_order:["evidence_f1","temporal_fidelity","edit_coverage","unsupported_claim_rate"],strongest_non_oracle_selection_metric:"evidence_f1",strongest_non_oracle_tie_order:["static_final_board","uniform_frame","transcript_only"],item_rater_aggregation:"equal_mean_two_raters",point_aggregation:"case_seed_mean_then_case_macro_then_video_macro_then_teacher_macro",bootstrap_method:"hierarchical_teacher_video_case_seed_paired_v2",bootstrap_seed:71,bootstrap_replicates:1000,primary_ci:.8,descriptive_ci:.95,quantile_method:"sorted_linear_interpolation_r7",missing_policy:"blocked_no_partial_statistics",zero_eligible_policy:"metric_null_and_gate_blocked",minimum_teachers:2,minimum_seeds_per_case:3} as const;
 const cap={rating_plan:{rating_plan_sha256:sha("7"),created_at:"2026-08-13T00:30:00.000Z",statistics_plan:statistics},rating_assignment:{assignment_sha256:sha("8"),run_sha256:sha("2"),formal_spec_sha256:sha("9"),terminal_checkpoint_sha256:sha("c"),run_completed_at:"2026-08-13T01:00:00.000Z"},public_evidence_package:{items:evidenceItems},rating_set:{rating_set_sha256:sha("b"),completed_at:"2026-08-13T01:30:00.000Z",ledgers:[{items:ledgerItems[0]},{items:ledgerItems[1]}]}} as unknown as TrustedOracleGateRatingSetCapabilityV1;
 const chain={run:{run_sha256:sha("2"),rating_plan_sha256:sha("7"),statistics_plan_sha256:sha("6"),formal_spec_sha256:sha("9")},intents:[],attempts:[],committed_requests:[],checkpoints:[{checkpoint_sha256:sha("c"),created_at:"2026-08-13T01:00:00.000Z"}],private_answer_key:key,public_blind_package:pub};
 return{pub,key,cap,chain,spec:{spec_sha256:sha("9"),seeds:[11,23,47]}};
}
describe("Formal Oracle Value Gate paired statistics",()=>{
 beforeEach(()=>vi.clearAllMocks());
 it("selects one Evidence-F1 baseline and deterministically compiles the preregistered paired GO rule",()=>{const x=fixture(),input={completed_run_artifact_chain:x.chain as never,trusted_ratings:x.cap,private_answer_key:x.key,public_blind_package:x.pub,formal_spec:x.spec as never,compiled_at:"2026-08-13T02:00:00.000Z",evidence_scope:"synthetic_test_fixture_not_result" as const};const a=compileOracleValueGateStatistics(input),b=compileOracleValueGateStatistics(input);expect(a).toEqual(b);expect(a.decision).toBe("GO");expect(a.selected_strongest_non_oracle).toBe("static_final_board");expect(a.metric_summaries).toHaveLength(4);expect(a.metric_summaries.every(m=>m.metric==="unsupported_claim_rate"?m.difference<=0:m.difference>=.05&&m.primary_80_ci[0]>0)).toBe(true);expect(a.paper_claim_status).toBe("prohibited_no_automatic_paper_claim");expect(a.api_execution_allowed).toBe(false);expect(Object.isFrozen(a.metric_summaries)).toBe(true);});
 it("blocks rather than partially compiling arm-specific denominator drift",()=>{const x=fixture();x.cap.public_evidence_package.items[1].claim_units[0].content="Different denominator";const report=compileOracleValueGateStatistics({completed_run_artifact_chain:x.chain as never,trusted_ratings:x.cap,private_answer_key:x.key,public_blind_package:x.pub,formal_spec:x.spec as never,compiled_at:"2026-08-13T02:00:00.000Z",evidence_scope:"synthetic_test_fixture_not_result"});expect(report.decision).toBe("BLOCKED");expect(report.metric_summaries).toEqual([]);expect(report.blocked_reasons.some(x=>x.startsWith("arm_denominator_drift"))).toBe(true);});
 it("blocks a self-consistent case whose seeds differ from the preregistered formal set",()=>{const x=fixture();for(const entry of x.key.entries)if(entry.seed===11)entry.seed=101;const report=compileOracleValueGateStatistics({completed_run_artifact_chain:x.chain as never,trusted_ratings:x.cap,private_answer_key:x.key,public_blind_package:x.pub,formal_spec:x.spec as never,compiled_at:"2026-08-13T02:00:00.000Z",evidence_scope:"synthetic_test_fixture_not_result"});expect(report.decision).toBe("BLOCKED");expect(report.blocked_reasons).toContain("formal_seed_set_drift:case-teacher-a");expect(report.blocked_reasons).toContain("formal_seed_set_drift:case-teacher-b");});
 it("rejects a rating plan created after the sealed generation-zero checkpoint",()=>{const x=fixture();(x.cap.rating_plan as {created_at:string}).created_at="2026-08-13T01:00:00.001Z";expect(()=>compileOracleValueGateStatistics({completed_run_artifact_chain:x.chain as never,trusted_ratings:x.cap,private_answer_key:x.key,public_blind_package:x.pub,formal_spec:x.spec as never,compiled_at:"2026-08-13T02:00:00.000Z",evidence_scope:"synthetic_test_fixture_not_result"})).toThrow(/generation-0/);});
 it("rejects caller accessors before running any chain validator",()=>{const x=fixture();let hits=0;const input={completed_run_artifact_chain:x.chain as never,trusted_ratings:x.cap,private_answer_key:x.key,public_blind_package:x.pub,formal_spec:x.spec as never,compiled_at:"2026-08-13T02:00:00.000Z",evidence_scope:"synthetic_test_fixture_not_result" as const};Object.defineProperty(input,"formal_spec",{enumerable:true,get(){hits++;return x.spec;}});expect(()=>compileOracleValueGateStatistics(input)).toThrow(/accessor/);expect(hits).toBe(0);expect(vi.mocked(assertActiveTrustedOracleGateRatingSetCapability)).not.toHaveBeenCalled();});
});
