import { describe, expect, it } from "vitest";
import {
  ORACLE_GATE_RESPONSE_SCHEMA_SHA256,
  FORMAL_ORACLE_USER_PROMPT_TEMPLATE_SHA256,
  FORMAL_ORACLE_USER_PROMPT_VERSION,
  hashFormalOraclePreregistrationBundleV2,
  hashFormalRunContractV2,
  hashOracleGateFormalSpecV2,
  hashOracleGatePublicEvidenceDerivationPolicyV2,
  hashOracleGateRatingPlanV2,
  hashOracleGateStatisticsPlanV2,
  validateFormalOraclePreregistrationBundleV2,
  validateFormalRunContractV2,
  validateFormalRunContractV2AgainstPreregistrationBundle,
  validateOracleGateStatisticsPlanV2,
  validateOracleGateRatingPlanV2AgainstFormalSpecV2,
  type FormalOraclePreregistrationBundleV2,
  type FormalRunContractV2,
  type OracleGateFormalSpecV2,
  type OracleGatePublicEvidenceDerivationPolicyV2,
  type OracleGateRatingPlanV2,
  type OracleGateStatisticsPlanV2,
} from "./index.js";

const sha = (character: string): string => character.repeat(64);
function policy(): OracleGatePublicEvidenceDerivationPolicyV2 {
  const value: OracleGatePublicEvidenceDerivationPolicyV2 = {
    schema_version:"oracle-gate-public-evidence-derivation-policy-v2",public_evidence_derivation_policy_sha256:sha("0"),claim_projection_version:"response-v1-fixed-json-pointer-assertion-slots-v1",
    claim_source_paths:["/observed_board_actions/*/operation","/observed_board_actions/*/content","/observed_board_actions/*/region","/generalized_teaching_capability/name","/generalized_teaching_capability/mechanism","/generalized_teaching_capability/action_program/*","/evidence_claims/*/claim"],uncertainty_policy:"not_a_scored_claim",
    speech_segmentation_version:"one_verified_selected_transcript_unit_per_case-v1",speech_gold_status:"context_not_gold",board_event_renderer_version:"signed-gold-final-event-semantic-projection-v1",board_event_projection:["operation","semantic_label","region","relation","modification"],
    eligible_evidence_policy:"verified_transcript_plus_all_signed_gold_final_events-v1",board_edit_denominator_policy:"all_signed_gold_final_events-v1",temporal_pair_policy:"all_ordered_signed_gold_final_event_pairs-v1",single_event_temporal_policy:"metric_not_applicable_not_global_block-v1",public_reblinding_scheme:"opaque-item-local-id-uniqueness-only-v1",created_at:"2026-08-13T00:00:00.000Z",api_execution_allowed:false,
  };value.public_evidence_derivation_policy_sha256=hashOracleGatePublicEvidenceDerivationPolicyV2(value);return value;
}
function fixture(): {bundle:FormalOraclePreregistrationBundleV2;run:FormalRunContractV2} {
  const p=policy();
  const statistics:OracleGateStatisticsPlanV2={schema_version:"oracle-gate-statistics-plan-v2",statistics_plan_sha256:sha("0"),record_trust:"non_authoritative_preregistered_statistics_plan",public_evidence_derivation_policy_sha256:p.public_evidence_derivation_policy_sha256,public_evidence_schema_version:"oracle-gate-public-evidence-package-v2",private_derivation_schema_version:"oracle-gate-private-evidence-derivation-receipt-v2",metric_order:["evidence_f1","temporal_fidelity","edit_coverage","unsupported_claim_rate"],strongest_non_oracle_selection_metric:"evidence_f1",strongest_non_oracle_tie_order:["static_final_board","uniform_frame","transcript_only"],item_rater_aggregation:"equal_mean_two_raters",point_aggregation:"case_seed_mean_then_case_macro_then_video_macro_then_teacher_macro",bootstrap_method:"hierarchical_teacher_video_case_seed_paired_v2",bootstrap_seed:71,bootstrap_replicates:1000,primary_ci:.8,descriptive_ci:.95,quantile_method:"sorted_linear_interpolation_r7",missing_policy:"blocked_no_partial_statistics",zero_eligible_policy:"metric_null_and_gate_blocked",single_event_temporal_policy:"exclude_temporal_item_symmetrically_within_case_seed_keep_other_metrics-v1",empty_temporal_population_policy:"blocked_no_temporal_population",minimum_teachers:2,minimum_seeds_per_case:3,created_at:"2026-08-13T00:00:00.000Z",api_execution_allowed:false};statistics.statistics_plan_sha256=hashOracleGateStatisticsPlanV2(statistics);
  const spec:OracleGateFormalSpecV2={schema_version:"oracle-gate-formal-spec-v2",spec_sha256:sha("0"),input_manifest_sha256:sha("1"),signed_gold_dataset_sha256:sha("2"),code_revision:"3".repeat(40),model:"fixture-model",transport:"pi",cache_retention:"none",tools_policy:"none",temperature:0,seeds:[11,23,47],prompt:{version:FORMAL_ORACLE_USER_PROMPT_VERSION,system_sha256:sha("4"),user_template_sha256:FORMAL_ORACLE_USER_PROMPT_TEMPLATE_SHA256,output_schema_sha256:ORACLE_GATE_RESPONSE_SCHEMA_SHA256},budget:{max_input_tokens:8192,max_output_tokens:2048,visual_items_per_visual_arm:1,canvas:{mime_type:"image/jpeg",width:1920,height:360,quality:88},timeout_ms:120000,max_attempts:2},evaluation:{rubric_version:"rubric-v2",rubric_sha256:sha("5"),rating_schema_version:"oracle-gate-rating-ledger-v2",independent_raters:2,primary_ci:.8,descriptive_ci:.95,bootstrap_seed:71,strongest_non_oracle_rule:"best_pre_registered_non_oracle_on_development",missing_request_policy:"fail_closed_no_partial_decision",public_evidence_derivation_policy_schema_version:"oracle-gate-public-evidence-derivation-policy-v2",public_evidence_derivation_policy_sha256:p.public_evidence_derivation_policy_sha256,statistics_plan_schema_version:"oracle-gate-statistics-plan-v2",statistics_plan_sha256:statistics.statistics_plan_sha256,public_evidence_schema_version:"oracle-gate-public-evidence-package-v2",private_derivation_schema_version:"oracle-gate-private-evidence-derivation-receipt-v2"},created_at:"2026-08-13T00:01:00.000Z"};spec.spec_sha256=hashOracleGateFormalSpecV2(spec);
  const rating:OracleGateRatingPlanV2={schema_version:"oracle-gate-rating-plan-v2",rating_plan_sha256:sha("0"),record_trust:"non_authoritative_preregistered_rating_plan",formal_spec_sha256:spec.spec_sha256,public_evidence_derivation_policy_sha256:p.public_evidence_derivation_policy_sha256,rubric_version:spec.evaluation.rubric_version,rubric_sha256:spec.evaluation.rubric_sha256,required_independent_raters:2,rating_schema_version:"oracle-gate-rating-ledger-v2",public_evidence_schema_version:"oracle-gate-public-evidence-package-v2",private_derivation_schema_version:"oracle-gate-private-evidence-derivation-receipt-v2",metrics:["evidence_f1","temporal_fidelity","edit_coverage","unsupported_claim_rate"],statistics_plan:structuredClone(statistics),statistics_plan_sha256:statistics.statistics_plan_sha256,created_at:"2026-08-13T00:02:00.000Z",api_execution_allowed:false};rating.rating_plan_sha256=hashOracleGateRatingPlanV2(rating);
  const bundle:FormalOraclePreregistrationBundleV2={schema_version:"formal-oracle-preregistration-bundle-v2",preregistration_bundle_sha256:sha("0"),record_trust:"non_authoritative_preregistration_bundle_external_worm_pending",policy:p,public_evidence_derivation_policy_sha256:p.public_evidence_derivation_policy_sha256,statistics_plan:statistics,statistics_plan_sha256:statistics.statistics_plan_sha256,formal_spec:spec,formal_spec_sha256:spec.spec_sha256,rating_plan:rating,rating_plan_sha256:rating.rating_plan_sha256,api_execution_allowed:false};bundle.preregistration_bundle_sha256=hashFormalOraclePreregistrationBundleV2(bundle);
  const run:FormalRunContractV2={schema_version:"oracle-gate-formal-run-contract-v2",run_sha256:sha("0"),canonicalization:"oracle-gate-run-canonical-json-v2",signed_gold_dataset_sha256:spec.signed_gold_dataset_sha256,formal_input_manifest_sha256:spec.input_manifest_sha256,formal_spec_sha256:spec.spec_sha256,schedule_sha256:sha("6"),execution_plan_sha256:sha("7"),ledger_registry_sha256:sha("8"),media_attestation_sha256:sha("9"),speech_attestation_sha256:sha("a"),code_revision:spec.code_revision,build_artifact_sha256:sha("b"),blinding_secret_commitment_sha256:sha("c"),blinding_scheme:"hmac-sha256-run-request-v1",rating_plan_sha256:rating.rating_plan_sha256,statistics_plan_sha256:statistics.statistics_plan_sha256,preregistration_bundle_sha256:bundle.preregistration_bundle_sha256,public_evidence_derivation_policy_sha256:p.public_evidence_derivation_policy_sha256,run_store_uri:"board2skill/formal-oracle-runs",request_count:12,directory_mode:"0700",file_mode:"0600",lock_scheme:"exclusive-create-owner-nonce-v1",checkpoint_scheme:"immutable-hash-chain-head-v1",remote_idempotency_mode:"local_only_fail_closed",api_execution_allowed:false};run.run_sha256=hashFormalRunContractV2(run);return{bundle,run};
}

describe("Formal Oracle preregistration v2",()=>{
  it("binds policy, statistics, spec, rating and run without a hash cycle",()=>{const x=fixture();expect(validateFormalOraclePreregistrationBundleV2(x.bundle)).toEqual({valid:true,issues:[]});expect(validateFormalRunContractV2(x.run)).toEqual({valid:true,issues:[]});expect(validateFormalRunContractV2AgainstPreregistrationBundle(x.run,x.bundle)).toEqual({valid:true,issues:[]});});
  it("rejects post-hoc root drift and statistics policy drift after full rehash",()=>{const x=fixture(),bad=structuredClone(x.bundle);bad.policy.created_at="2026-08-13T00:03:00.000Z";bad.policy.public_evidence_derivation_policy_sha256=hashOracleGatePublicEvidenceDerivationPolicyV2(bad.policy);bad.public_evidence_derivation_policy_sha256=bad.policy.public_evidence_derivation_policy_sha256;bad.preregistration_bundle_sha256=hashFormalOraclePreregistrationBundleV2(bad);expect(validateFormalOraclePreregistrationBundleV2(bad).valid).toBe(false);const stats=structuredClone(x.bundle);stats.statistics_plan.single_event_temporal_policy="metric_not_applicable_not_global_block-v1" as never;stats.statistics_plan.statistics_plan_sha256=hashOracleGateStatisticsPlanV2(stats.statistics_plan);stats.statistics_plan_sha256=stats.statistics_plan.statistics_plan_sha256;stats.preregistration_bundle_sha256=hashFormalOraclePreregistrationBundleV2(stats);expect(validateFormalOraclePreregistrationBundleV2(stats).valid).toBe(false);});
  it("rejects V1 rename impersonation, unknown fields and accessors before execution",()=>{const x=fixture(),rename={...x.bundle.formal_spec,schema_version:"oracle-gate-formal-spec-v1"};expect(validateFormalOraclePreregistrationBundleV2({...x.bundle,formal_spec:rename}).valid).toBe(false);expect(validateFormalRunContractV2({...x.run,extra:true}).valid).toBe(false);let hits=0;const hostile=Object.create(Object.prototype,Object.getOwnPropertyDescriptors(x.bundle));Object.defineProperty(hostile,"policy",{enumerable:true,get(){hits++;return x.bundle.policy;}});expect(validateFormalOraclePreregistrationBundleV2(hostile).valid).toBe(false);const hostileStats=Object.create(Object.prototype,Object.getOwnPropertyDescriptors(x.bundle.statistics_plan));Object.defineProperty(hostileStats,"created_at",{enumerable:true,get(){hits++;return x.bundle.statistics_plan.created_at;}});expect(validateOracleGateStatisticsPlanV2(hostileStats).valid).toBe(false);expect(hits).toBe(0);});
  it("rejects nested FormalSpec extras and split bootstrap authority after full rehash",()=>{const x=fixture();const nested=structuredClone(x.bundle);(nested.formal_spec.budget.canvas as unknown as Record<string,unknown>).extra="authority-looking";nested.formal_spec.spec_sha256=hashOracleGateFormalSpecV2(nested.formal_spec);nested.formal_spec_sha256=nested.formal_spec.spec_sha256;nested.rating_plan.formal_spec_sha256=nested.formal_spec.spec_sha256;nested.rating_plan.rating_plan_sha256=hashOracleGateRatingPlanV2(nested.rating_plan);nested.rating_plan_sha256=nested.rating_plan.rating_plan_sha256;nested.preregistration_bundle_sha256=hashFormalOraclePreregistrationBundleV2(nested);expect(validateFormalOraclePreregistrationBundleV2(nested).valid).toBe(false);const split=structuredClone(x.bundle);split.statistics_plan.bootstrap_seed=72;split.statistics_plan.statistics_plan_sha256=hashOracleGateStatisticsPlanV2(split.statistics_plan);split.statistics_plan_sha256=split.statistics_plan.statistics_plan_sha256;split.formal_spec.evaluation.statistics_plan_sha256=split.statistics_plan_sha256;split.formal_spec.spec_sha256=hashOracleGateFormalSpecV2(split.formal_spec);split.formal_spec_sha256=split.formal_spec.spec_sha256;split.rating_plan.formal_spec_sha256=split.formal_spec_sha256;split.rating_plan.statistics_plan=structuredClone(split.statistics_plan);split.rating_plan.statistics_plan_sha256=split.statistics_plan_sha256;split.rating_plan.rating_plan_sha256=hashOracleGateRatingPlanV2(split.rating_plan);split.rating_plan_sha256=split.rating_plan.rating_plan_sha256;split.preregistration_bundle_sha256=hashFormalOraclePreregistrationBundleV2(split);expect(validateFormalOraclePreregistrationBundleV2(split).valid).toBe(false);});
  it("rejects split bootstrap authority through the exported plan/spec cross-validator",()=>{const x=fixture();const plan=structuredClone(x.bundle.rating_plan),spec=structuredClone(x.bundle.formal_spec);plan.statistics_plan.bootstrap_seed=72;plan.statistics_plan.statistics_plan_sha256=hashOracleGateStatisticsPlanV2(plan.statistics_plan);plan.statistics_plan_sha256=plan.statistics_plan.statistics_plan_sha256;spec.evaluation.statistics_plan_sha256=plan.statistics_plan_sha256;spec.spec_sha256=hashOracleGateFormalSpecV2(spec);plan.formal_spec_sha256=spec.spec_sha256;plan.rating_plan_sha256=hashOracleGateRatingPlanV2(plan);expect(validateOracleGateRatingPlanV2AgainstFormalSpecV2(plan,spec).valid).toBe(false);});
});
