import { createHash, createHmac } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { validateOracleGateResponse, type OracleGateResponseArm } from "../packages/contracts/src/oracle-gate-response.js";
import { hashOracleGateRequest, renderOracleGateUserPrompt } from "../packages/distillation/src/oracleGateRunner.js";
import { buildOraclePilotPackage } from "../packages/distillation/src/oraclePilot.js";
import type { OraclePilotArmInput } from "../packages/distillation/src/oraclePilot.js";
import type { BoardEvidenceBundle } from "../packages/contracts/src/index.js";
import { canonicalizeOracleGateCanvas } from "../packages/media/src/oracleGateCanvas.js";
import { verifyImageEvidence } from "../packages/media/src/imageEvidence.js";

type Arm = OracleGateResponseArm;
interface Block { version_tag:"prompt-v1"|"prompt-v2";root:string;run:string;spec:string;seed:number;seed_index:number;expected_spec_sha256?:string;expected_manifest_sha256?:string;expected_blind_sha256?:string;expected_records_sha256?:string;expected_pilot_sha256?:string;expected_key_sha256?:string }
interface Spec { schema_version:string;protocol_scope:string;protocol_document:string;prompt_version:string;blind_seed_sha256:string;generation_seed:number;seed_index:number;cases:Array<{case_id:string;delta_id:string;uniform_frame_id:string}> }
interface Manifest { schema_version:string;decision:string;model:string;protocol_fingerprint_sha256:string;prompt_sha256:string;output_schema_sha256:string;case_count:number;arm_count:number;seed_count:number;request_count:number;warning:string }
interface KeyItem { blind_id:string;paired_case_id:string;case_id:string;arm:Arm;seed:number;condition_sha256:string }
interface BlindItem { blind_id:string;paired_case_id:string;seed_index:number;response:Record<string,unknown>;response_sha256:string }
interface RecordItem extends KeyItem { run_id:string;response:Record<string,unknown>;response_sha256:string;request_audit:{request_sha256:string;model:string;attempt_count:number;submitted_visuals:Array<{label:string;sha256:string;mime_type:string;byte_length:number}>;provider_response_received:boolean;stop_reason:string;usage:unknown;transport:string;temperature:number;max_output_tokens:number;seed:number;cache_retention:string;tools_policy:string};canonical_visual:null|{source_asset_uri:string;source_sha256:string;submitted_sha256:string;mime_type:string;width:number;height:number;transform:string} }
interface Pilot { schema_version:string;bundle_id:string;protocol:{protocol_version:string;prompt_version:string;visual_items_per_visual_arm:number;speech_window_seconds:number;visual_budget_rule:string;runtime_pixel_and_token_audit_required:boolean};samples:OraclePilotArmInput[];answer_key:Array<{blind_id:string;paired_case_id:string;case_id:string;arm:Arm;evidence_mode:string;condition_sha256:string}>;blind_evaluation_items:unknown[] }
interface PublicItem { blind_id:string;response:Record<string,unknown>;response_sha256:string;evidence_card:{schema_version:"ly004-blind-evidence-v1";evidence_units:Array<{unit_id:string;kind:"transcript"|"board_edit";content:string}>;target_operation:"ADD";temporal_fidelity:"not_applicable_single_event";question_recovery:{friction:"required"|"not_applicable";acceleration:"required"|"not_applicable"}} }

const root=process.cwd();
const outputRoot=resolve(root,"data/board2skill/oracle-gate-prompt-paired-diagnostic");
const bundleRoot=resolve(root,"data/board2skill/gold-dev/tbv2-ly-004-01-gold-dev-v2");
const bundle=JSON.parse(await readFile(join(bundleRoot,"bundle.json"),"utf8")) as BoardEvidenceBundle;
const jointKeyPath=join(outputRoot,"private/joint-blind-seed.txt");
const protocolPath=resolve(root,"research/board2skill/experiments/LY004_PROMPT_V1_V2_PAIRED_DIAGNOSTIC_V1.md");
const JOINT_KEY_SHA="55f0c1a1815f24165e3433a42baf4ea95fbddd10c151e6a8d0d05a79993d5f49";
const PREREG_COMMIT="717ada6";
const PROTOCOL_SHA="e992862abb490ab632e6ca63cb72e4d53f95bbd955d703135fd666e659b192d3";
const TEMPLATE_SHA="e2d70a4072b837096affffb647c6e3f4f54c13d7ea38c908d946991caba19266";
const BUNDLE_BYTES_SHA="28b452ff69aa9145e8f82dbf7e9a57545c2ffdffeb8495065ee050339d408e9d";
const JOINT_ID_DOMAIN="skyclass/ly004-prompt-paired-diagnostic/joint-blind-id/v1\0";
const MATRIX_DOMAIN="skyclass/ly004-prompt-paired-diagnostic/matrix/v1\0";
const PRIVATE_MAP_DOMAIN="skyclass/ly004-prompt-paired-diagnostic/private-map/v1\0";
const ORDER_DOMAINS={R1:"skyclass/ly004-prompt-paired-diagnostic/rater-order/r1/v1\0",R2:"skyclass/ly004-prompt-paired-diagnostic/rater-order/r2/v1\0"} as const;
const ARMS:Arm[]=["transcript_only","static_final_board","uniform_frame","oracle_delta"];
const BLIND_SEED_SHA="3c78aab1296ba6f1f9c93f4df24df02e8982ad25fa86bcc765ef6ba6fc34bc3e";
const MODEL="gpt-5.5",SCHEMA_SHA="99ff47e5ea52494303b0acc7b6d3128b0c51a90f2451a396a60a05c5de932a11";
const PROMPTS={"prompt-v1":{version:"oracle-gate-prompt-v1",sha:"38cdf0bfad57415873b0d17572eebe592d8ec348571a38254a68dace84d5d080"},"prompt-v2":{version:"oracle-gate-prompt-v2-region-claim-decoupled",sha:"32687e49703780c42d2c5cb582011b59d86a2faf632f8e9930ca0e38234aa2f6"}} as const;
const EXPECTED_CASES=[{case_id:"ly004-known-condition",delta_id:"B-DELTA-05",uniform_frame_id:"GOLD-UNIFORM-01"},{case_id:"ly004-question-pair",delta_id:"B-DELTA-06",uniform_frame_id:"GOLD-UNIFORM-02"}];
const BLOCKS:Block[]=[
  {version_tag:"prompt-v1",root:"data/board2skill/oracle-gate-development",run:"run-01",spec:"research/board2skill/experiments/ly004-development-seed-01.json",seed:20260814,seed_index:0,expected_spec_sha256:"0e57376c934f4290ad98f674da9c7806d8c8bbf9ea79a02fccc865154bff2856",expected_manifest_sha256:"b51b4abb7cf3ef602b482960f0bbbacaa16f540335e7de11ecab57ef9a467f80",expected_blind_sha256:"2293b1e46bfeb84e5e7fc226ec1a622fc74a5e5718bd8149c057d88f9e66ea14",expected_records_sha256:"7a56568a2d4c62a7a1c73d3a690c41fba3163a0d327fd12d7e809c2a01dd0385",expected_pilot_sha256:"d180f8bf33429ffeb7769feb5bdea3a76f90161306309c9adceefb4a42ece09f",expected_key_sha256:"fc820c7aec7c404c7c89c8dfb3a4ff94303945d338347f7b0e38b6eb7e4d3f37"},
  {version_tag:"prompt-v1",root:"data/board2skill/oracle-gate-development",run:"run-03",spec:"research/board2skill/experiments/ly004-development-seed-03.json",seed:20260816,seed_index:2,expected_spec_sha256:"563752f33a56870bec85d96e8a58777c7342808254a5b7a42d387fe7ab8548f2",expected_manifest_sha256:"8caa8da0e02c5ac55fdc79f7aa6d699553ffd63a43a2ce3e09f0d86743b3b1ea",expected_blind_sha256:"49535c78090f26504e1ef04314172c9ba8fd2288c8b144621a7e093045574b82",expected_records_sha256:"188ba6c353186d4819220990863bac50a40de48e78a48f2e548a52f85b7c114d",expected_pilot_sha256:"d180f8bf33429ffeb7769feb5bdea3a76f90161306309c9adceefb4a42ece09f",expected_key_sha256:"05ad6916a9795cd52ba9ab7273dd5057f92279b3b03c97e058acfd9374d53d22"},
  {version_tag:"prompt-v1",root:"data/board2skill/oracle-gate-development",run:"run-04",spec:"research/board2skill/experiments/ly004-development-seed-04.json",seed:20260817,seed_index:3,expected_spec_sha256:"d03092896ae69c27c4901b634eb3ce2149c37f670fad2dce408fd6bd61c627c0",expected_manifest_sha256:"9a1bf687e88b0b3d19e019bb3dee52a3042300f66b8b0ec44b8dcdb42b8237d8",expected_blind_sha256:"a3ed41585790853f981bd623352a265b610a74f7b418ee2ee585a33e901a94b7",expected_records_sha256:"6f439388e435ad3bf8100526db834ef7b9c44d4929e6cd631477c8f76d207343",expected_pilot_sha256:"d180f8bf33429ffeb7769feb5bdea3a76f90161306309c9adceefb4a42ece09f",expected_key_sha256:"6e6864d6a1447e4c5c403a37e0d8d4f480fd83effb2074fff68d9742caf4f52b"},
  {version_tag:"prompt-v2",root:"data/board2skill/oracle-gate-prompt-paired-diagnostic",run:"v2-run-01",spec:"research/board2skill/experiments/ly004-prompt-v2-paired-seed-01.json",seed:20260814,seed_index:0,expected_spec_sha256:"05eeb73a253bd8d0a4dac01eb1a74670d96fce3e76e127b239ef720cd1403596"},
  {version_tag:"prompt-v2",root:"data/board2skill/oracle-gate-prompt-paired-diagnostic",run:"v2-run-02",spec:"research/board2skill/experiments/ly004-prompt-v2-paired-seed-02.json",seed:20260816,seed_index:2,expected_spec_sha256:"dbcd7da3d7b0af1c88022644d75fc4450d2524f50a583494d00733d73a240267"},
  {version_tag:"prompt-v2",root:"data/board2skill/oracle-gate-prompt-paired-diagnostic",run:"v2-run-03",spec:"research/board2skill/experiments/ly004-prompt-v2-paired-seed-03.json",seed:20260817,seed_index:3,expected_spec_sha256:"8629888cb022154db3ac2d075e651902108d7b1ff8c0334c3ccd4d46957e3aad"},
];
const EVIDENCE:Record<string,Omit<PublicItem["evidence_card"],"schema_version">>={
  "ly004-known-condition":{evidence_units:[{unit_id:"T1",kind:"transcript",content:"教师陈述支持力等于 1.2mg。"},{unit_id:"T2",kind:"transcript",content:"教师随后提出摩擦力和加速度两个问题。"},{unit_id:"B1",kind:"board_edit",content:"目标板书编辑为 ADD：N = 1.2mg。"}],target_operation:"ADD",temporal_fidelity:"not_applicable_single_event",question_recovery:{friction:"not_applicable",acceleration:"not_applicable"}},
  "ly004-question-pair":{evidence_units:[{unit_id:"T1",kind:"transcript",content:"教师陈述支持力等于 1.2mg。"},{unit_id:"T2",kind:"transcript",content:"教师提出摩擦力大小问题。"},{unit_id:"T3",kind:"transcript",content:"教师提出加速度大小问题。"},{unit_id:"B1",kind:"board_edit",content:"目标板书编辑为 ADD：f=? 与 a=? 两个待求量。"}],target_operation:"ADD",temporal_fidelity:"not_applicable_single_event",question_recovery:{friction:"required",acceleration:"required"}},
};
function assert(v:unknown,m:string):asserts v{if(!v)throw new Error(m);}function sha(v:string|Buffer):string{return createHash("sha256").update(v).digest("hex");}
function stable(v:unknown):string{if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(stable).join(",")}]`;const o=v as Record<string,unknown>;return`{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${stable(o[k])}`).join(",")}}`;}
function lines<T>(b:Buffer):T[]{return b.toString("utf8").trim().split("\n").filter(Boolean).map(x=>JSON.parse(x) as T);}function exact(v:Record<string,unknown>,k:string[],l:string){assert(stable(Object.keys(v).sort())===stable([...k].sort()),`${l}字段不精确`);}
function normalize(v:string):string{return v.normalize("NFKC").replace(/\p{Default_Ignorable_Code_Point}/gu,"").replace(/\s+/gu,"").toLowerCase();}
function collectStringsAndKeys(v:unknown,out:string[]=[]):string[]{if(typeof v==="string")out.push(v);else if(Array.isArray(v))v.forEach(x=>collectStringsAndKeys(x,out));else if(v&&typeof v==="object")for(const [k,x] of Object.entries(v as Record<string,unknown>)){out.push(k);collectStringsAndKeys(x,out);}return out;}
function fingerprint(promptSha:string,seed:number):string{return sha(JSON.stringify({model:MODEL,prompt_sha256:promptSha,output_schema_sha256:SCHEMA_SHA,temperature:0,max_output_tokens:2048,cache_retention:"none",transport:"pi",tools_policy:"none",canvas:{mime_type:"image/jpeg",width:1920,height:360,quality:88},seeds:[seed]}));}
const jointKey=await readFile(jointKeyPath);assert(jointKey.length===65&&sha(jointKey)===JOINT_KEY_SHA,"joint seed原始字节承诺无效");
assert(sha(await readFile(protocolPath))===PROTOCOL_SHA&&sha(await readFile(resolve(root,"research/board2skill/experiments/ly004-prompt-paired-diagnostic-rating-template-v1.csv")))===TEMPLATE_SHA&&sha(await readFile(join(bundleRoot,"bundle.json")))===BUNDLE_BYTES_SHA,"预注册协议/模板/bundle root漂移");
const publicItems:PublicItem[]=[],privateItems:Array<Record<string,unknown>>=[],sourceRoots:Array<Record<string,unknown>>=[];
for(const block of BLOCKS){const source=resolve(root,block.root,block.run);const specBytes=await readFile(resolve(root,block.spec)),manifestBytes=await readFile(join(source,"manifest.json")),blindBytes=await readFile(join(source,"blind/items.jsonl")),recordsBytes=await readFile(join(source,"private/run-records.jsonl")),pilotBytes=await readFile(join(source,"private/input-pilot.json")),keyBytes=await readFile(join(source,"private/answer-key.json"));
  for(const [actual,expected,label] of [[sha(specBytes),block.expected_spec_sha256,"spec"],[sha(manifestBytes),block.expected_manifest_sha256,"manifest"],[sha(blindBytes),block.expected_blind_sha256,"blind"],[sha(recordsBytes),block.expected_records_sha256,"records"],[sha(pilotBytes),block.expected_pilot_sha256,"pilot"],[sha(keyBytes),block.expected_key_sha256,"key"]] as const)if(expected)assert(actual===expected,`${block.run}历史${label} root漂移`);
  const spec=JSON.parse(specBytes.toString("utf8")) as Spec,manifest=JSON.parse(manifestBytes.toString("utf8")) as Manifest,pilot=JSON.parse(pilotBytes.toString("utf8")) as Pilot,keys=JSON.parse(keyBytes.toString("utf8")) as KeyItem[],blinds=lines<BlindItem>(blindBytes),records=lines<RecordItem>(recordsBytes);const prompt=PROMPTS[block.version_tag];
  exact(spec as unknown as Record<string,unknown>,["schema_version","protocol_scope","protocol_document","prompt_version","blind_seed_sha256","generation_seed","seed_index","cases"],`${block.run} spec`);spec.cases.forEach((x,i)=>exact(x as unknown as Record<string,unknown>,["case_id","delta_id","uniform_frame_id"],`${block.run} spec case ${i}`));exact(manifest as unknown as Record<string,unknown>,["schema_version","decision","model","protocol_fingerprint_sha256","prompt_sha256","output_schema_sha256","case_count","arm_count","seed_count","request_count","warning"],`${block.run} manifest`);exact(pilot as unknown as Record<string,unknown>,["schema_version","bundle_id","protocol","samples","blind_evaluation_items","answer_key"],`${block.run} pilot`);exact(pilot.protocol as unknown as Record<string,unknown>,["protocol_version","prompt_version","visual_items_per_visual_arm","speech_window_seconds","visual_budget_rule","runtime_pixel_and_token_audit_required"],`${block.run} pilot protocol`);keys.forEach((x,i)=>exact(x as unknown as Record<string,unknown>,["blind_id","paired_case_id","case_id","arm","seed","condition_sha256"],`${block.run} key ${i}`));blinds.forEach((x,i)=>exact(x as unknown as Record<string,unknown>,["blind_id","paired_case_id","seed_index","response","response_sha256"],`${block.run} blind ${i}`));records.forEach((x,i)=>{exact(x as unknown as Record<string,unknown>,["run_id","blind_id","paired_case_id","case_id","arm","seed","condition_sha256","response_sha256","response","request_audit","canonical_visual"],`${block.run} record ${i}`);exact(x.request_audit as unknown as Record<string,unknown>,["request_sha256","model","attempt_count","submitted_visuals","provider_response_received","stop_reason","usage","transport","temperature","max_output_tokens","seed","cache_retention","tools_policy"],`${block.run} audit ${i}`);});pilot.samples.forEach((x,i)=>exact(x as unknown as Record<string,unknown>,["case_id","arm","evidence_mode","source_video_id","delta_id","time","speech_ids","transcript","evidence_text","image_assets","paired_context_sha256","condition_sha256"],`${block.run} sample ${i}`));
  assert(spec.schema_version==="oracle-gate-smoke-spec-v1"&&spec.generation_seed===block.seed&&spec.seed_index===block.seed_index&&spec.blind_seed_sha256===BLIND_SEED_SHA&&spec.prompt_version===prompt.version&&stable(spec.cases)===stable(EXPECTED_CASES),`${block.run} spec漂移`);assert(manifest.schema_version==="oracle-gate-smoke-manifest-v1"&&manifest.decision==="not_evaluable"&&manifest.warning==="engineering_wiring_smoke_not_an_experiment_result"&&manifest.model===MODEL&&manifest.prompt_sha256===prompt.sha&&manifest.output_schema_sha256===SCHEMA_SHA&&manifest.protocol_fingerprint_sha256===fingerprint(prompt.sha,block.seed)&&manifest.case_count===2&&manifest.arm_count===4&&manifest.seed_count===1&&manifest.request_count===8,`${block.run} manifest漂移`);assert(pilot.protocol.prompt_version===prompt.version&&keys.length===8&&blinds.length===8&&records.length===8&&pilot.samples.length===8,`${block.run} source计数/协议漂移`);const expectedPilot=buildOraclePilotPackage({bundle,cases:spec.cases,prompt_version:prompt.version,blind_seed:await readFile(resolve(root,"data/board2skill/oracle-gate-development/private/seed.txt"),"utf8").then(x=>x.trim())});assert(stable(pilot)===stable(expectedPilot),`${block.run} pilot未由冻结bundle/spec确定性推出`);const expectedKeyByCell=new Map(expectedPilot.answer_key.map(x=>[`${x.case_id}\0${x.arm}`,x]));
  const blindMap=new Map(blinds.map(x=>[x.blind_id,x])),recordMap=new Map(records.map(x=>[x.blind_id,x]));for(const key of keys){const blind=blindMap.get(key.blind_id),record=recordMap.get(key.blind_id),sample=pilot.samples.find(x=>x.case_id===key.case_id&&x.arm===key.arm),expectedKey=expectedKeyByCell.get(`${key.case_id}\0${key.arm}`);assert(blind&&record&&sample&&expectedKey,`${block.run} source集合不闭合`);const expectedRunBlind=`B-${sha(JSON.stringify({blind_id:expectedKey.blind_id,seed:block.seed})).slice(0,20)}`,expectedRunPair=`P-${sha(JSON.stringify({paired_case_id:expectedKey.paired_case_id,seed:block.seed})).slice(0,20)}`;assert(key.blind_id===expectedRunBlind&&key.paired_case_id===expectedRunPair&&key.condition_sha256===expectedKey.condition_sha256&&key.seed===block.seed&&blind.paired_case_id===key.paired_case_id&&blind.seed_index===0&&record.run_id===`RUN-${sha(JSON.stringify({condition:key.condition_sha256,seed:block.seed})).slice(0,20)}`&&record.paired_case_id===key.paired_case_id&&record.seed===block.seed&&record.case_id===key.case_id&&record.arm===key.arm&&record.condition_sha256===key.condition_sha256&&sample.condition_sha256===key.condition_sha256,`${block.run} source identity漂移`);assert(record.request_audit.attempt_count===1&&record.request_audit.provider_response_received===true&&record.request_audit.stop_reason==="stop"&&record.request_audit.seed===block.seed&&record.request_audit.model===MODEL&&record.request_audit.temperature===0&&record.request_audit.max_output_tokens===2048&&record.request_audit.cache_retention==="none"&&record.request_audit.tools_policy==="none"&&record.request_audit.transport==="pi",`${block.run} audit漂移`);assert(stable(record.response)===stable(blind.response)&&record.response_sha256===blind.response_sha256&&sha(JSON.stringify(blind.response))===blind.response_sha256,`${block.run} response漂移`);validateOracleGateResponse(blind.response,key.arm);
    const images:Array<{label:string;bytes:Buffer;mime_type:"image/jpeg";sha256:string}>=[];if(key.arm==="transcript_only")assert(record.canonical_visual===null&&record.request_audit.submitted_visuals.length===0,`${block.run} transcript visual漂移`);else{assert(sample.image_assets.length===1&&record.canonical_visual&&record.request_audit.submitted_visuals.length===1,`${block.run} visual缺失`);const asset=sample.image_assets[0],verified=await verifyImageEvidence({root:bundleRoot,assetUri:asset.asset_uri,expectedSha256:asset.sha256}),canvas=canonicalizeOracleGateCanvas(verified.bytes,key.arm);const auditVisual=record.request_audit.submitted_visuals[0];assert(record.canonical_visual.source_asset_uri===asset.asset_uri&&record.canonical_visual.source_sha256===asset.sha256&&record.canonical_visual.submitted_sha256===canvas.sha256&&auditVisual.sha256===canvas.sha256&&auditVisual.byte_length===canvas.bytes.byteLength,`${block.run} visual derivation漂移`);images.push({label:"visual-1",bytes:canvas.bytes,mime_type:"image/jpeg",sha256:canvas.sha256});}
    const user=renderOracleGateUserPrompt(sample,prompt.version),requestSha=hashOracleGateRequest({model:MODEL,user,temperature:0,control:{transport:"pi",maxOutputTokens:2048,seed:block.seed,cacheRetention:"none"},images});assert(record.request_audit.request_sha256===requestSha,`${block.run} request root漂移`);
    const manifestSha=sha(manifestBytes),preimage={original_blind_id:key.blind_id,source_run_manifest_sha256:manifestSha,version_tag:block.version_tag},jointId=`J-${createHmac("sha256",jointKey).update(JOINT_ID_DOMAIN+stable(preimage)).digest("hex").slice(0,24)}`;const evidence=EVIDENCE[key.case_id];assert(evidence,"未知case");publicItems.push({blind_id:jointId,response:blind.response,response_sha256:blind.response_sha256,evidence_card:{schema_version:"ly004-blind-evidence-v1",...evidence}});privateItems.push({blind_id:jointId,version_tag:block.version_tag,generation_seed:block.seed,case_id:key.case_id,arm:key.arm,original_blind_id:key.blind_id,original_paired_case_id:key.paired_case_id,source_run_manifest_sha256:manifestSha,source_run:block.run});
  }
  sourceRoots.push({version_tag:block.version_tag,generation_seed:block.seed,spec_sha256:sha(specBytes),manifest_sha256:sha(manifestBytes),blind_sha256:sha(blindBytes),records_sha256:sha(recordsBytes),pilot_sha256:sha(pilotBytes),answer_key_sha256:sha(keyBytes)});
}
assert(publicItems.length===48&&new Set(publicItems.map(x=>x.blind_id)).size===48,"联合盲包必须48项/48 unique");assert(privateItems.length===48,"private map必须48项");const publicById=new Map(publicItems.map(x=>[x.blind_id,x]));assert(publicById.size===48,"public id碰撞");
const cells=new Set(privateItems.map(x=>`${x.version_tag}\0${x.generation_seed}\0${x.case_id}\0${x.arm}`));assert(cells.size===48,"private map必须精确覆盖2×3×2×4");const privateValues=new Set(privateItems.flatMap(x=>Object.entries(x).filter(([k,v])=>k!=="blind_id"&&typeof v==="string").map(([,v])=>normalize(v as string))));for(const item of publicItems){for(const value of collectStringsAndKeys(item)){if(value===item.blind_id)continue;const normalized=value.normalize("NFKC").replace(/\p{Default_Ignorable_Code_Point}/gu,"").toLowerCase(),n=normalize(value);assert(!/(promptv[12]|transcriptonly|staticfinalboard|uniformframe|oracledelta|pairedcaseid|caseid|requestid|runid|generationseed|versiontag)/u.test(n)&&!/(arm|seed|case|run|request|pair|paired|pairing|version|condition|臂|种子|案例|请求|运行|配对|版本|条件)[:=：]/u.test(n)&&!/paired\s*with|pairing\s*(with|to)|与.{0,8}(响应|项目|条目).{0,4}配对/u.test(normalized),`${item.blind_id}公开字段泄漏实验结构`);for(const secret of privateValues)if(secret.length>=6)assert(!n.includes(secret),`${item.blind_id}公开文本包含私有值`);}}
const ordered=Object.fromEntries((Object.keys(ORDER_DOMAINS) as Array<keyof typeof ORDER_DOMAINS>).map(r=>{const items=[...publicItems].sort((a,b)=>sha(ORDER_DOMAINS[r]+a.blind_id).localeCompare(sha(ORDER_DOMAINS[r]+b.blind_id)));return[r,{items,bytes:items.map(x=>JSON.stringify(x)).join("\n")+"\n"}];})) as Record<"R1"|"R2",{items:PublicItem[];bytes:string}>;assert(ordered.R1.items.map(x=>x.blind_id).join()!==ordered.R2.items.map(x=>x.blind_id).join(),"R1/R2展示顺序不得相同");
const privatePayload={schema_version:"ly004-prompt-paired-private-map-payload-v1",items:[...privateItems].sort((a,b)=>String(a.blind_id).localeCompare(String(b.blind_id)))};const privateSha=sha(PRIVATE_MAP_DOMAIN+stable(privatePayload));const matrix={preregistration_commit:PREREG_COMMIT,protocol_document_sha256:PROTOCOL_SHA,rating_template_sha256:TEMPLATE_SHA,bundle_bytes_sha256:BUNDLE_BYTES_SHA,joint_seed_sha256:JOINT_KEY_SHA,item_count:48,version_count:2,case_count:2,arm_count:4,seed_count:3,source_roots:sourceRoots,private_map_payload_sha256:privateSha,rater_item_roots:{R1:sha(ordered.R1.bytes),R2:sha(ordered.R2.bytes)}};const matrixSha=sha(MATRIX_DOMAIN+stable(matrix));
await rm(join(outputRoot,"blind-package"),{recursive:true,force:true});await mkdir(join(outputRoot,"blind-package/r1"),{recursive:true});await mkdir(join(outputRoot,"blind-package/r2"),{recursive:true});await mkdir(join(outputRoot,"private"),{recursive:true,mode:0o700});for(const r of ["R1","R2"] as const){const lower=r.toLowerCase();await writeFile(join(outputRoot,`blind-package/${lower}/items.jsonl`),ordered[r].bytes,"utf8");await writeFile(join(outputRoot,`blind-package/${lower}/manifest.json`),JSON.stringify({schema_version:"ly004-prompt-paired-rater-view-v1",rater_id:r,item_count:48,items_sha256:sha(ordered[r].bytes),matrix_receipt_sha256:matrixSha},null,2)+"\n","utf8");}
await writeFile(join(outputRoot,"blind-package/manifest.json"),JSON.stringify({schema_version:"ly004-prompt-paired-blind-package-v1",matrix_receipt_domain:MATRIX_DOMAIN,matrix_receipt_sha256:matrixSha,matrix,rater_views:["r1","r2"]},null,2)+"\n","utf8");await writeFile(join(outputRoot,"private/rating-map-v1.json"),JSON.stringify({schema_version:"ly004-prompt-paired-private-map-v1",matrix_receipt_sha256:matrixSha,private_map_payload_sha256:privateSha,items:privatePayload.items},null,2)+"\n",{encoding:"utf8",mode:0o600});console.log(JSON.stringify({items:48,matrix_receipt_sha256:matrixSha,r1_sha256:sha(ordered.R1.bytes),r2_sha256:sha(ordered.R2.bytes)}));
